### ISSUE TITLE
This code is being plagiarised

### ISSUE THREAD

**Issue by vipulrai91** [HendrikStrobelt/detecting-fake-text#12]
https://github.com/llSourcell/Watch-Me-Build-an-Education-Startup

Wanted to get the attention of the original authors on this.
It hurts to see the people who worked hard for this not being credited and some wannabe ml guru taking credit for this. 

I did not have any other medium to report this , sorry if this is not an appropriate place.

**Comment by HendrikStrobelt** [comment]
Thank you for bringing this to our attention. It's a shame to see such behavior.

**Comment by BasicHtmlCoder** [comment]
😂😆😁😂😆😁😂😆😁😂😆😁😂😆😁😂😆😁

**Comment by BasicHtmlCoder** [comment]
SUBSCRIBE I SAID !!

<img width="1314" height="668" alt="Image" src="https://github.com/user-attachments/assets/9c3ff493-df28-42c1-a0b8-0f90e58dfd83" />
