### ISSUE TITLE
Demo at http://gltr.io/dist/index.html returns 500

### ISSUE THREAD

**Issue by CT83** [HendrikStrobelt/detecting-fake-text#2]
![image](https://user-images.githubusercontent.com/17134097/68372248-7e91d580-0166-11ea-9846-5d6c5d1972ba.png)

Great work on the Repo, Guys!!!

I was trying the demo but noticed that it did not work for me. Maybe you could please look into it?

**Comment by CT83** [comment]
@HendrikStrobelt fixed this!! Whoo!

**Comment by thesofakillers** [comment]
Hi, perhaps we need to reopen this issue. I am getting the same exact error, even on longer text.
